Add Apache Kafka basic support
yandex/yandex-taxi-testsuite pull request #105
Opened 2024-09-16 12:09 UTC by fdr400

Adds Kafka service and producer fixture

2024-09-20 14:48 UTC, vitek requested changes

2024-09-20 14:48 UTC, vitek commented on docs/kafka.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
тильд должно быть столько же, сколько символов в заголовке, здесь и ниже

2024-09-20 14:48 UTC, vitek commented on tests/conftest.py
> +    # Kafka
давай в tests/kafka/conftest.py перенесем

2024-09-20 14:48 UTC, vitek commented on testsuite/databases/kafka/classes.py
> +        timeout_ms: int = 3000,
давай просто timeout в секундах, как в остальных местах testsuite

2024-09-20 14:48 UTC, vitek commented on testsuite/databases/kafka/pytest_plugin.py
> +    event_loop.run_until_complete(producer.start())
тут надо делать через asynccontextmanager

2024-09-20 14:48 UTC, vitek commented on testsuite/databases/kafka/pytest_plugin.py
> +    event_loop.run_until_complete(producer.start())
а не дорого создавать клиента на каждый тест?

2024-09-20 14:48 UTC, vitek commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
а чего так много изменений? может проще с собой конфиг таскать?

2024-09-20 14:48 UTC, vitek commented on testsuite/databases/kafka/scripts/service-kafka
> +    PIDS=$(ps ax | grep ' kafka\.Kafka ' | grep java | grep -v grep | awk '{print $1}'| xargs)
точно ли нужен такой сложный код?

2024-09-20 14:52 UTC, fdr400 commented on tests/conftest.py
> +    # Kafka
Имеешь в виду kafka_custom_topics перенести? или подключение плагина тоже?

2024-09-20 14:55 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
но его же всё равно нужно будет патчить под окружение
или ты это предлагаешь в питоновском коде делать?

вообще, не знаю, почему в Кафке не поддержали override конфига на все скрипты.. Из-за этого такая морока получается

2024-09-20 15:00 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    PIDS=$(ps ax | grep ' kafka\.Kafka ' | grep java | grep -v grep | awk '{print $1}'| xargs)
Ну, я его скопировал из скрипта остановки сервера Кафки
И почти весь скрипт скопировал только пропатчил

Если бы можно было как-то записать pid сервера в файл, тогда бы было всё намного проще и работал бы stop_daemon, но это Кафка не поддержала :(

Если запускать дефолтный скрипт, то он грохнет все Кафки на машине
Как иначе правильно определить процесс, который убивать, я не знаю и в интернете почти ничего не нашёл по этому поводу

2024-09-20 15:07 UTC, fdr400 commented on testsuite/databases/kafka/pytest_plugin.py
> +    event_loop.run_until_complete(producer.start())
Мне показалось, что так надёжнее и понятнее, плюс создаются они быстро

У консьюмер стейтфул, поэтому не хотелось бы, чтобы его состояния шарились между тестами

Продьюсер в каком-то смысле тоже, потому что он внутри себя буфферизирует сообщения, и если тест свалится, то сообщения по идее могут в следующем тесте только дойти

2024-09-20 15:29 UTC, fdr400 commented on docs/kafka.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
зафиксил

2024-09-20 15:34 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +        timeout_ms: int = 3000,
поменял на секунды

2024-09-20 15:38 UTC, fdr400 commented on tests/conftest.py
> +    # Kafka
перенёс kafka_custom_topics в tests/databases/kafka/conftest.py

2024-09-20 16:31 UTC, fdr400 commented on testsuite/databases/kafka/pytest_plugin.py
> +    event_loop.run_until_complete(producer.start())
сделал

2024-09-20 17:36 UTC, fdr400 commented on testsuite/databases/kafka/pytest_plugin.py
> +    event_loop.run_until_complete(producer.start())
сделал, чтобы создавались по одному на всю сессию, а после каждого теста продьюсер -- флашился, а консьюмер -- всё коммитили и отписывался от всего, на что подписался

2024-09-23 15:05 UTC, vitek requested changes

2024-09-23 15:05 UTC, vitek commented on .github/workflows/ci.yml
> +        sudo apt-get install -y default-jre
а почему это не засунуть в Install kafka? думаешь кому-то еще пригодится?

2024-09-23 15:05 UTC, vitek commented on tests/databases/kafka/test_producer_consumer_basic.py
> +        logging.info(f'Received batch of {len(consumed_messages)} messages')
в logging надо использовать встроенное форматирование `logging.info('...%d...', len(...))`, т.к. это может повлиять на перформанс

2024-09-23 15:05 UTC, vitek commented on testsuite/databases/kafka/classes.py
> +        timeout: int = 3,
а почему не float, в python обычно float используют

2024-09-23 15:05 UTC, vitek commented on testsuite/databases/kafka/pytest_plugin.py
> +    async with _create_producer(
а в чем смысл выносить в отдельную функцию это? как будто можно было бы тут и start позвать и teardown

2024-09-23 15:05 UTC, vitek commented on testsuite/databases/kafka/classes.py
> +    async def teardown(self):
обычно это называют close, но можно stop

2024-09-23 15:07 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +        timeout: int = 3,
там у функции aiokafka таймаут в интах принимается

2024-09-23 15:08 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +    async def teardown(self):
тут взял из rabbitmq, могу заменить

2024-09-24 07:21 UTC, fdr400 commented on .github/workflows/ci.yml
> +        sudo apt-get install -y default-jre
Да нет, перенёс в Install Kafka

2024-09-24 07:27 UTC, fdr400 commented on tests/databases/kafka/test_producer_consumer_basic.py
> +        logging.info(f'Received batch of {len(consumed_messages)} messages')
fixed

2024-09-24 07:29 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +        timeout: int = 3,
а, ну кстати можно зафиксить всё-таки, там таймаут в миллисекундах

2024-09-24 07:30 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +        timeout: int = 3,
fixed

2024-09-24 08:06 UTC, fdr400 commented on testsuite/databases/kafka/pytest_plugin.py
> +    async with _create_producer(
оставил только глобальную фикстуру, туда добавил async with compat.aclosing

2024-09-24 08:07 UTC, fdr400 commented on testsuite/databases/kafka/classes.py
> +    async def teardown(self):
заменил на aclosing

2024-09-24 13:30 UTC, vitek requested changes

2024-09-24 13:30 UTC, vitek commented on setup.cfg
> +version = 0.2.3
это тебе не надо трогать, я сам запущу релиз, после мержа

2024-09-24 13:37 UTC, fdr400 commented on setup.cfg
> +version = 0.2.3
ой, блин, это я локально так тестил, нечаянно запушил

2024-09-24 16:27 UTC, merged