set proper default for macos
yandex/yandex-taxi-testsuite pull request #109
Opened 2024-12-27 12:19 UTC by fdr400

2025-01-07 16:04 UTC, vitek requested changes

2025-01-07 16:04 UTC, vitek commented on tests/plugins/mockserver/test_unix_mockserver.py
> +if platform.system() == 'Darwin':
а почему так?

2025-01-07 16:04 UTC, vitek commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i.bak 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
а что .bak начит?

2025-01-07 16:04 UTC, vitek commented on testsuite/databases/kafka/service.py
> +    _KAFKA_HOME_DEFAULT = '/opt/homebrew/opt/kafka/libexec'
может тут все-таки лучше искать подходящий путь? из нескольких вариантов? и почему бы это не унести вообще в sh скрипт?

2025-01-07 16:04 UTC, vitek commented on testsuite/databases/rabbitmq/service.py
> +if platform.system() == 'Darwin':
унеси в sh скрипт

2025-01-07 16:15 UTC, fdr400 commented on tests/plugins/mockserver/test_unix_mockserver.py
> +if platform.system() == 'Darwin':
На макосе ограничение в длине имени юникс-сокета буквально на пару символов меньше, чем на Линуксе
Поэтому нужно, чтобы имя было короче
Я гуглил такие проблемы, там примерно везде такое решение и было

2025-01-07 16:23 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i.bak 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
я честно не до конца понимаю, но я таким образом сделал, чтобы в Аркадии рецепт Кафки работал и для маков, и для линукса
На Линуксе sed от GNU, а на маке какой-то свой очень ограниченный, и по какой-то причине такая штука поддерживает совместимость

в принципе на мак можно установить GNUшные утилиты, но это как будто лишнее и там не так просто детектировать их отсутствие

2025-01-07 16:23 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i.bak 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
хочется, чтобы из коробки всё работало

2025-01-07 16:28 UTC, fdr400 commented on testsuite/databases/kafka/scripts/find-kafka.sh
> -        version=$("$_java" -version 2>&1 | grep -oP 'version "?(1\.)?\K\d+')
на маке у grep нет части удобных опций, поэтому заменил на другой регексп

2025-01-08 07:40 UTC, fdr400 commented on testsuite/databases/kafka/service.py
> +    _KAFKA_HOME_DEFAULT = '/opt/homebrew/opt/kafka/libexec'
унёс в скрипт

2025-01-08 07:40 UTC, fdr400 commented on testsuite/databases/rabbitmq/service.py
> +if platform.system() == 'Darwin':
тоже унёс

2025-01-08 07:50 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i.bak 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
в общем, это типа суффикс имени файла, в которым нужно делать бэкап при inplace замене
в Линуксе бэкап опционален, а в Маке -- обязательный

2025-01-08 07:51 UTC, fdr400 commented on testsuite/databases/kafka/scripts/service-kafka
> +    sed -i.bak 's/log\.dirs=.*/log\.dirs='"$(echo "$KAFKA_LOGS_DIR" | sed 's/\//\\\//g')"'/' "$KAFKA_CONF_FILE"
сделал .backup

2025-01-09 09:21 UTC, vitek requested changes

2025-01-09 09:21 UTC, vitek commented on testsuite/databases/kafka/scripts/find-kafka.sh
> +    echo "
тебя не смущает, что печать будет с отступами? я бы рекомендовал привести все к одному виду

2025-01-09 09:21 UTC, vitek commented on testsuite/databases/rabbitmq/scripts/find-rabbitmq.sh
> +if [ "$(uname)" = "Darwin" ]; then
у нас вроде везде 4 отступа в скриптах

2025-01-09 09:21 UTC, vitek commented on testsuite/databases/kafka/scripts/find-kafka.sh
> +    if [ ! -x "$1/bin/kafka-run-class.sh" ]; then
можно просто так

```
check_home() {
    [ -x "$1/bin/kafka-run-class.sh" ] && [ -e "$1/config/kraft/server.properties" ]
}
```

2025-01-09 10:26 UTC, fdr400 commented on testsuite/databases/kafka/scripts/find-kafka.sh
> +    echo "
поправил

2025-01-09 10:26 UTC, fdr400 commented on testsuite/databases/rabbitmq/scripts/find-rabbitmq.sh
> +if [ "$(uname)" = "Darwin" ]; then
тоже поправил

2025-01-09 10:26 UTC, fdr400 commented on testsuite/databases/kafka/scripts/find-kafka.sh
> +    if [ ! -x "$1/bin/kafka-run-class.sh" ]; then
done

2025-01-10 11:20 UTC, vitek approved these changes

2025-01-10 11:20 UTC, vitek commented on tests/plugins/mockserver/test_unix_mockserver.py
> +if platform.system() == 'Darwin':
можно было бы mockserver.sock или как-то так называть

2025-01-10 11:20 UTC, vitek commented on testsuite/databases/kafka/scripts/find-kafka.sh
> +    echo "
кстати, такое можно еще делать через cat:

```
function foo() {
    cat <<EOF
my very long line...
...
EOF
}

2025-01-10 11:26 UTC, merged