feat http: parse multipart/form-data
yandex/yandex-taxi-testsuite pull request #17
Opened 2022-11-18 10:09 UTC by segoon

2022-11-18 15:22 UTC, sazikov-ad commented on testsuite/utils/http.py
> +            elif self._request.content_type.startswith('multipart/form-data'):
Кажется, будет лучше вынести из form отдельно, например в multipart

2022-11-18 15:22 UTC, sazikov-ad commented on testsuite/utils/http.py
> +                data = email.message_from_string(epost_data)
И вместо либы, можно использовать  `self._request.multipart()`(https://docs.aiohttp.org/en/stable/web_reference.html?highlight=BaseRequest#aiohttp.web.BaseRequest.multipart).

И возвращать обертку над https://docs.aiohttp.org/en/stable/multipart_reference.html?highlight=BodyPartReader#aiohttp.BodyPartReader
с методами `name`, `headers`, `json`, `get_data` (и возможно, filename)

2022-11-19 18:29 UTC, sazikov-ad commented on testsuite/utils/http.py
> +                data = email.message_from_string(epost_data)
upd: похоже через aiohttp не получится, из-за асинхронности

2022-11-21 07:00 UTC, segoon commented on testsuite/utils/http.py
> +            elif self._request.content_type.startswith('multipart/form-data'):
а зачем? как раз хорошо, что общий интерфейс у разных content types, мы тут абстрагируемся от этого

2022-11-21 07:00 UTC, segoon commented on testsuite/utils/http.py
> +                data = email.message_from_string(epost_data)
в итоге, email.message_from_string - ок?

2022-11-21 13:00 UTC, sazikov-ad approved these changes

2022-11-21 13:03 UTC, vitek requested changes

2022-11-21 13:03 UTC, vitek commented on testsuite/utils/http.py
> +                epost_data = (
можно вынести в константу?

2022-11-21 13:03 UTC, vitek commented on testsuite/utils/http.py
> +import email
нужно написать тесты

2022-11-21 16:10 UTC, segoon commented on testsuite/utils/http.py
> +                epost_data = (
вынес

2022-11-21 16:10 UTC, segoon commented on testsuite/utils/http.py
> +import email
написал

2022-11-21 16:26 UTC, merged