feat utils: add matching.PartialDict
yandex/yandex-taxi-testsuite pull request #30
Opened 2023-03-24 13:15 UTC by Dahaka934

2023-03-24 22:19 UTC, Dahaka934 commented on testsuite/utils/matching.py
> +        return self._dict.get(item, Any())
Это сомнительный хак, конечно (возврат Any(), если нет элемента и True в contains).

Но это позволяет скипать вывод полей в "Extra fields in the left/right, которых нет в PartialDict.

2023-03-24 22:23 UTC, Dahaka934 commented on tests/utils/test_matching.py
> +    assert not (sample != matching.PartialDict(some_int=1))
Выглядит, как бесполезный тест, но

В реализации PartialDict через наследование от dict, если не перегрузить `__ne__`, этот тест не пройдет. Поэтому решил оставить.

2023-03-26 05:00 UTC, vitek requested changes

2023-03-26 05:00 UTC, vitek commented on tests/utils/test_matching.py
> +    sample = dict(some_int=1, some_str='abc', some_dict=dict(a=5, b='b', c=6))
sample = {...}

2023-03-26 05:00 UTC, vitek commented on testsuite/utils/matching.py
> +        if not isinstance(other, collections.abc.Mapping):
а это точно надо? не достаточно просто упасть, если keys нету?

2023-03-26 05:00 UTC, vitek commented on testsuite/utils/matching.py
> +        return self._dict.__iter__()
iter(self._dict), дальше аналогично

2023-03-26 12:57 UTC, Dahaka934 commented on testsuite/utils/matching.py
> +        if not isinstance(other, collections.abc.Mapping):
Это будет что-то странное
Если ожидался dict (и чекаем через PartialDict), а по факту значение - str. Кмк, должно отрабатывать адекватно.

2023-03-27 09:02 UTC, vitek commented on testsuite/utils/matching.py
> +        if not isinstance(other, collections.abc.Mapping):
по идее, если падает оператор сравнения, значит объекты не равны, но давай пока так оставим

2023-03-27 09:07 UTC, vitek requested changes

2023-03-27 09:07 UTC, vitek commented on testsuite/plugins/assertrepr_compare.py
> +    if issubclass(obj_type, matching.PartialDict):
не стоит ли тут сделать проверку на abc?

2023-03-27 09:07 UTC, vitek commented on testsuite/utils/matching.py
> +        return repr(self._dict)
наверное тут лучше все-таки сделать свой репр <PartialDict: ...>

2023-03-27 09:07 UTC, vitek commented on testsuite/utils/matching.py
> +        for key in self.keys():
давай тут сделаем `for key in self`

2023-03-27 09:07 UTC, vitek commented on testsuite/utils/matching.py
> +        return self._dict.get(item, Any())
можем сделать any-синглтон и уже его тут использовать?

2023-03-27 09:11 UTC, Dahaka934 commented on testsuite/utils/matching.py
> +        return repr(self._dict)
думаешь, стоит? тогда diff будет страшнее

2023-03-27 10:44 UTC, vitek approved these changes

2023-03-27 11:52 UTC, merged