feat redis: add redis cluster support
yandex/yandex-taxi-testsuite pull request #36
Opened 2023-04-11 12:38 UTC by VyacheslavVanin

2023-05-29 08:51 UTC, vitek requested changes

2023-05-29 08:51 UTC, vitek commented on tests/databases/redis/test_cluster.py
> +@pytest.fixture(scope='session')
why do you need it here? it's already defined in redis/pytest_plugin

2023-05-29 08:51 UTC, vitek commented on tests/databases/redis/test_sentinel.py
> +@pytest.fixture(scope='session')
same

2023-05-29 08:51 UTC, vitek commented on testsuite/databases/redis/configs/redis_cluster_node.conf.tpl
> +
extra new line at EOF

2023-05-29 08:51 UTC, vitek commented on testsuite/databases/redis/pytest_plugin.py
> +    finally:
you don't need finally here

2023-05-29 08:51 UTC, vitek commented on testsuite/databases/redis/pytest_plugin.py
> +def cluster_redis_sentinels(pytestconfig, _redis_service_settings):
redis related fixtures must have common prefix

2023-05-29 08:51 UTC, vitek commented on testsuite/databases/redis/service.py
> +        if len(self.cluster_ports) < len(DEFAULT_CLUSTER_PORTS):
what would you do if more than len(...) ports given?

2023-05-29 08:51 UTC, vitek commented on testsuite/databases/redis/service.py
> +    cluster_ports: typing.Tuple[int, ...]
do sentinel redis and cluster redis share same fields? If they don't please split into two classes

2023-05-30 13:22 UTC, VyacheslavVanin commented on tests/databases/redis/test_cluster.py
> +@pytest.fixture(scope='session')
removed

2023-05-30 13:22 UTC, VyacheslavVanin commented on tests/databases/redis/test_sentinel.py
> +@pytest.fixture(scope='session')
removed

2023-05-30 13:44 UTC, vitek requested changes

2023-05-30 13:44 UTC, vitek commented on tests/plugins/test_cluster_redis.py
> +def _check_store_file(redis_cluster_store):
turn into a fixture

2023-05-30 13:44 UTC, vitek commented on testsuite/databases/redis/genredis.py
> +    if redis_version() >= [3, 2, 0]:
use version tuple instead

2023-05-30 13:44 UTC, vitek commented on testsuite/databases/redis/pytest_plugin.py
> +def redis_cluster_store(
please share code with redis_store() instead of copy-pasting

2023-05-30 13:44 UTC, vitek commented on testsuite/databases/redis/scripts/service-cluster-redis
> +REDIS_SERVER=$(which redis-server)
2> /dev/null

you can add helper function to utils.sh, e.g.:

```bash
find_binary() {
    which "$1" 2> /dev/null
}

```

2023-05-31 16:18 UTC, vitek approved these changes

2023-05-31 16:44 UTC, merged