mysql speedup
yandex/yandex-taxi-testsuite pull request #53
Opened 2023-08-22 04:30 UTC by 1kovalevskiy

2023-10-05 08:42 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                        for (t,) in self.tables
а ты тестировал этот кусок кода?

2023-10-05 08:48 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                truncate_sql = ' '.join(
можно в цикл развернуть?

2023-10-05 09:34 UTC, 1kovalevskiy commented on testsuite/databases/mysql/control.py
> +                        for (t,) in self.tables
Поправил

2023-10-05 09:42 UTC, 1kovalevskiy commented on testsuite/databases/mysql/control.py
> +                truncate_sql = ' '.join(
Сделал в цикле

2023-10-05 16:03 UTC, 1kovalevskiy commented on testsuite/databases/mysql/control.py
> +        self._need_save_tables = True
Заметил, что попытка применить миграцию запускается на каждый тест, поэтому добавил дополнительный флаг, который сообщает, что миграция действительно выполнилась и надо перезаписать список таблиц

2023-10-06 07:09 UTC, vitek commented on testsuite/databases/mysql/control.py
> +        self._need_save_tables = False
как будто надо флаг выставлять в конце, у тебя может упасть код ниже

2023-10-06 11:29 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                    cursor.execute(query.body, args=[])
тут не нужны аргументы

2023-10-06 11:29 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                truncate_sql = ' '.join(
во вложенном? я имел ввиду сделать обычный цикл

2023-10-06 14:59 UTC, 1kovalevskiy commented on testsuite/databases/mysql/control.py
> +                truncate_sql = ' '.join(
Посмотри, пожалуйста
Это то, что ты имел ввиду?
Если нет, то можешь немного конкретизировать, а то я не понял?

2023-10-09 08:36 UTC, vitek requested changes

2023-10-09 08:36 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                        for (t,) in self._tables
а почему у тебя tables - это не список таблиц? может после fetch надо его в список строк превращать?

2023-10-09 08:36 UTC, vitek commented on testsuite/databases/mysql/control.py
> +                subquery = ' union '.join(
```
queries = []
for table in self._tables:
    queries.append(
        f'select \'{t}\' as name, count(*) as c from {t}'
    )
subquery = ' union '.join(queries)
query = f'select name from ({subquery}) tables where c>0;'
```

2023-10-09 08:36 UTC, vitek commented on testsuite/databases/mysql/control.py
> +        self._tables: typing.Optional[typing.List[str]] = tables
почему optional? давай сделаем List[str]

2023-10-09 08:36 UTC, vitek commented on testsuite/databases/mysql/control.py
> +            self._tables[dbname] = cursor.fetchall()
тут результат надо привести к типу List[str]

2023-10-09 13:09 UTC, vitek approved these changes

2023-10-09 14:49 UTC, merged