Reliable get_free_port()
yandex/yandex-taxi-testsuite pull request #80
Opened 2024-03-10 18:25 UTC by apolukhin

2024-03-12 13:03 UTC, vitek requested changes

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +def _get_ipv6_af_or_fallback():
а тут не стоит ли закешировать результат?

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +    try:
with contextlib.closing(sock) ...

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +    try:
contextlib.closing()

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +    sock_list = set()
а почему не []?

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +        return _get_free_port_sock_storing(
а мне кажется, что 0 на всех платформах должен выдавать рандомный порт

2024-03-12 13:03 UTC, vitek commented on testsuite/plugins/network.py
> +        nonlocal port
хорошо бы обойтись без nonlocal, можно например так:

```
port_seq = itertools.count(61000)

next(port_seq)
```

2024-03-13 10:13 UTC, apolukhin commented on testsuite/plugins/network.py
> +def _get_ipv6_af_or_fallback():
Как я понимаю фикстура на сессию отработает только один раз за запуск тестов

2024-03-13 10:25 UTC, apolukhin commented on testsuite/plugins/network.py
> +        return _get_free_port_sock_storing(
Да, но нет жесткой гарантии что оно не вернёт тот же порт, если старый сокет закрыли
```
    sock = socket.socket(socket_af, socket.SOCK_STREAM)
    with contextlib.closing(sock):
        sock.bind((host, 0))
        port1 = sock.getsockname()[

    sock = socket.socket(socket_af, socket.SOCK_STREAM)
    with contextlib.closing(sock):
        sock.bind((host, 0))
        port2 = sock.getsockname()[1]

    assert port1 != port2
```

Так что тут перестраховался... Можем всегда идти по ветке _get_free_port_sock_storing, но оаставить _get_free_port_range_based на всякий пожарный.

Ну или лучше добавить MacOS и проверить что там инваринт сохраняется (имеющийся тест кстати проверяет этот кейс)

2024-03-13 11:12 UTC, vitek approved these changes

2024-03-13 11:12 UTC, merged